# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:12.2.6"
  amd64: "ghcr.io/hassio-addons/base/amd64:12.2.6"
  armhf: "ghcr.io/hassio-addons/base/armhf:12.2.6"
  armv7: "ghcr.io/hassio-addons/base/armv7:12.2.6"
  i386: "ghcr.io/hassio-addons/base/i386:12.2.6"
labels:
  org.opencontainers.image.title: "Whatsapp Add-on"
  org.opencontainers.image.description: "Whatsapp integration for Home Assistant."
  org.opencontainers.image.source: "https://github.com/gajosu/whatsapp-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2022.09.1"
