# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Whatsapp
version: "1.2.14"
slug: whatsapp
description: Whatsapp integration for Home Assistant.
url: "https://github.com/gajosu/whatsapp-ha-addon/tree/master/whatsapp"
arch:
  # - armhf
  # - armv7
  # - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: The webserver port (Not used for Ingress).

image: "ghcr.io/gajosu/{arch}-whatsapp-ha-addon"